<?php $this->displayTemplate('header') ?>

<script type="text/javascript">
<!--
var default_iso = '<?php echo $this->session->shopCountry ?>';
-->
</script>

<!-- Configuration form -->
<div id="infosShopBlock">
	<h2><?php echo $this->l('Information about your Store') ?></h2>

	<!-- Shop name -->
	<div class="field clearfix">
		<label for="infosShop" class="aligned"><?php echo $this->l('Shop name') ?> </label>
		<div class="contentinput">
			<input class="text required" type="text" id="infosShop" name="shopName" value="<?php echo htmlspecialchars($this->session->shopName) ?>" /> <sup class="required">*</sup>
		</div>
		<?php echo $this->displayError('shopName') ?>
	</div>

	<!-- Activity -->
	<div class="field clearfix">
		<label for="infosActivity" class="aligned"><?php echo $this->l('Main activity') ?></label>
		<div class="contentinput">
			<select id="infosActivity" name="shopActivity" class="chosen">
				<option value="0" style="font-weight: bold" <?php if (!$this->session->shopActivity): ?>selected="selected"<?php endif; ?>><?php echo $this->l('Please choose your main activity') ?></option>
				<?php foreach ($this->listActivities as $i => $activity): ?>
					<option value="<?php echo $i ?>" <?php if (isset($this->session->shopActivity) && $this->session->shopActivity == $i): ?>selected="selected"<?php endif; ?>><?php echo $activity ?></option>
				<?php endforeach; ?>
				<option value="0"><?php echo $this->l('Other activity...') ?></option>
			</select>
		</div>
		<p class="userInfos aligned"><?php echo $this->l('Help us learn more about your store so we can offer you optimal guidance and the best features for your business!') ?></p>
	</div>

	<!-- Install type (with fixtures or not) -->
	<div class="field clearfix">
		<label class="aligned"><?php echo $this->l('Install demo products') ?></label>
		<div class="contentinput">
			<label>
				<input value="full" type="radio" name="dbMode" style="vertical-align: middle;" <?php if ($this->installType == 'full'): ?>checked="checked"<?php endif; ?> autocomplete="off" />
				<?php echo $this->l('Yes') ?>
			</label>
			<label>
				<input value="lite" type="radio" name="dbMode" style="vertical-align: middle;" <?php if ($this->installType == 'lite'): ?>checked="checked"<?php endif; ?> autocomplete="off" />
				<?php echo $this->l('No'); ?>
			</label>
		</div>
		<p class="userInfos aligned"><?php echo $this->l('Demo products are a good way to learn how to use thirty bees. You should install them if you are not familiar with it.') ?></p>
	</div>

	<!-- Country list -->
	<div class="field clearfix">
		<label for="infosCountry" class="aligned"><?php echo $this->l('Country') ?></label>
		<div class="contentinput">
			<select name="shopCountry" id="infosCountry" class="chosen">
				<option value="0" style="font-weight: bold"><?php echo $this->l('Select your country') ?></option>
				<?php foreach ($this->listCountries as $country): ?>
					<option value="<?php echo (isset($country['iso'])) ? $country['iso'] : '' ?>" <?php if ($this->session->shopCountry && isset($country['iso']) && $this->session->shopCountry === $country['iso']): ?>selected="selected"<?php endif; ?>><?php echo $country['name'] ?></option>
				<?php endforeach; ?>
			</select>
			<sup class="required">*</sup>
		</div>
		<?php echo $this->displayError('shopCountry') ?>
	</div>

	<!-- Timezone list -->
	<div id="timezone_div" class="field clearfix" <?php if (!in_array($this->session->shopTimezone, ['us','ca','au','ru','me','id'])) echo 'style="display:none"'; ?>>
		<label for="infosTimezone" class="aligned"><?php echo $this->l('Shop timezone') ?></label>
		<div class="contentinput">
			<select name="shopTimezone" id="infosTimezone" class="chosen no-chosen">
				<option value="0" style="font-weight: bold"><?php echo $this->l('Select your timezone') ?></option>
				<?php foreach ($this->getTimezones() as $timezone): ?>
					<option value="<?php echo $timezone ?>" <?php if ($this->session->shopTimezone == $timezone): ?>selected="selected"<?php endif; ?>><?php echo $timezone ?></option>
				<?php endforeach; ?>
			</select>
			<sup class="required">*</sup>
		</div>
		<?php echo $this->displayError('shopTimezone') ?>
	</div>

	<h2 style="margin-top:20px"><?php echo $this->l('Your Account') ?></h2>

	<!-- Admin firstname -->
	<div class="field clearfix">
		<label for="infosFirstname" class="aligned"><?php echo $this->l('First name') ?> </label>
		<div class="contentinput">
			<input class="text required" type="text" id="infosFirstname" name="adminFirstname" value="<?php echo htmlspecialchars($this->session->adminFirstname) ?>" />
			<sup class="required">*</sup>
		</div>
		<?php echo $this->displayError('adminFirstname') ?>
	</div>

	<!-- Admin lastname -->
	<div class="field clearfix">
		<label for="infosName" class="aligned"><?php echo $this->l('Last name') ?> </label>
		<div class="contentinput">
			<input class="text required" type="text" id="infosName" name="adminLastname" value="<?php echo htmlspecialchars($this->session->adminLastname) ?>" />
			<sup class="required">*</sup>
		</div>
		<?php echo $this->displayError('adminLastname') ?>
	</div>

	<!-- Admin email -->
	<div class="field clearfix">
		<label for="infosEmail" class="aligned"><?php echo $this->l('E-mail address') ?> </label>
		<div class="contentinput">
			<input type="text" class="text required" id="infosEmail" name="adminEmail" value="<?php echo htmlspecialchars($this->session->adminEmail) ?>" />
			<sup class="required">*</sup>
		</div>
		<p class="userInfos aligned"><?php echo $this->l('This email address will be your username to access your store\'s back office.') ?></p>
		<?php echo $this->displayError('adminEmail') ?>
	</div>

	<!-- Admin password -->
	<div class="field clearfix">
		<label for="infosPassword" class="aligned"><?php echo $this->l('Shop password') ?> </label>
		<div class="contentinput">
			<input autocomplete="off" type="password" class="text required" id="infosPassword" name="adminPassword" value="<?php echo htmlspecialchars($this->session->adminPassword) ?>" />
			<sup class="required">*</sup>
		</div>
		<?php if ($this->displayError('adminPassword')): ?>
			<?php echo $this->displayError('adminPassword') ?>
		<?php else: ?>
			<p class="userInfos aligned"><?php echo $this->l('Must be at least 8 characters') ?></p>
		<?php endif; ?>
	</div>

	<!-- Admin password confirm -->
	<div class="field clearfix">
		<label class="aligned" for="infosPasswordRepeat"><?php echo $this->l('Re-type to confirm') ?> </label>
		<div class="contentinput">
			<input type="password" autocomplete="off" class="text required" id="infosPasswordRepeat" name="adminPasswordConfirm" value="<?php echo htmlspecialchars($this->session->adminPasswordConfirm) ?>" />
			<sup class="required">*</sup>
		</div>
		<?php echo $this->displayError('adminPasswordConfirm') ?>
	</div>
	<br />
	<span><small><?php echo sprintf($this->l('All information you give us is collected by us and is subject to data processing and statistics, it is necessary for the members of the thirty bees company in order to respond to your requests. Your personal data may be communicated to service providers and partners as part of partner relationships. Under the current "Act on Data Processing, Data Files and Individual Liberties" you have the right to access, rectify and oppose to the processing of your personal data through this <a href="%s" onclick="return !window.open(this.href)">link</a>.'), 'mailto:legal@thirtybees.com'); ?></small></span>
</div>

<!-- Partners form -->
<div id="benefitsBlock" style="display:none"></div>

<?php $this->displayTemplate('footer') ?>
