<?php $this->displayTemplate('header') ?>

<!-- Database configuration -->
<div id="dbPart">
	<h2><?php echo $this->l('Configure your database by filling out the following fields') ?></h2>
	<p>
		<?php echo $this->l('To use thirty bees, you must create a database to collect all of your store\'s data-related activities.') ?>
		<br />
		<?php echo $this->l('Please complete the fields below in order for thirty bees to connect to your database. ') ?>
	</p>

	<div id="formCheckSQL">
		<p class="first" style="margin-top: 15px;">
			<label for="dbServer"><?php echo $this->l('Database server address') ?> </label>
			<input size="25" class="text" type="text" id="dbServer" name="dbServer" value="<?php echo htmlspecialchars($this->databaseServer) ?>" />
			<span class="userInfos aligned"><?php echo $this->l('The default port is 3306. To use a different port, add the port number at the end of your server\'s address i.e ":4242".') ?></span>
		</p>
		<p>
			<label for="dbName"><?php echo $this->l('Database name') ?> </label>
			<input size="10" class="text" type="text" id="dbName" name="dbName" value="<?php echo htmlspecialchars($this->databaseName) ?>" />
		</p>
		<p>
			<label for="dbLogin"><?php echo $this->l('Database login') ?> </label>
			<input class="text" size="10" type="text" id="dbLogin" name="dbLogin" value="<?php echo htmlspecialchars($this->databaseLogin) ?>" />
		</p>
		<p>
			<label for="dbPassword"><?php echo $this->l('Database password') ?> </label>
			<input class="text" size="10" type="password" id="dbPassword" name="dbPassword" value="<?php echo htmlspecialchars($this->databasePassword) ?>" />
		</p>
		<p>
			<label for="db_prefix"><?php echo $this->l('Tables prefix')?></label>
			<input class="text" type="text" id="db_prefix" name="db_prefix" value="<?php echo htmlspecialchars($this->databasePrefix) ?>" />
		</p>
		<?php if (_PS_MODE_DEV_): ?>
			<p>
				<label for="db_clear"><?php echo $this->l('Drop existing tables (mode dev)')?></label>
				<input type="checkbox" name="database_clear" id="db_clear" value="1" <?php if ($this->databaseClear): ?>checked="checked"<?php endif; ?> />
			</p>
		<?php endif; ?>
		<p class="aligned last">
			<input id="btTestDB" class="button" type="button" value="<?php echo $this->l('Test your database connection now!') ?>"/>
		</p>
		
		<input class="text" type="hidden" id="rewrite_engine" name="rewrite_engine" value="0" />

		<?php if ($this->errors): ?>
			<p id="dbResultCheck" class="errorBlock"><?php echo implode('<br />', $this->errors) ?></p>
		<?php else: ?>
			<p id="dbResultCheck" style="display: none;"></p>
		<?php endif; ?>
	</div>
</div>

<?php $this->displayTemplate('footer') ?>
