<?php $this->displayTemplate('header') ?>

<!-- License agreement -->
<h2 id="licenses-agreement"><?php echo $this->l('License Agreements') ?></h2>
<p><strong><?php echo $this->l('To enjoy the many features that are offered for free by thirty bees, please read the license terms below. thirty bees core is licensed under OSL 3.0, while the modules and themes are licensed under AFL 3.0.') ?></strong></p>
<div style="height:200px; border:1px solid #ccc; margin-bottom:8px; padding:5px; background:#fff; overflow: auto; overflow-x:hidden; overflow-y:scroll;">
<?php $this->displayTemplate('license_content'); ?>
</div>

<div>
	<input type="checkbox" id="set_license" class="required" name="license_agreement" value="1" style="vertical-align: middle;float:left" <?php if ($this->session->licenseAgreement): ?>checked="checked"<?php endif; ?> />
	<div style="float:left;width:600px;margin-left:8px"><label for="set_license"><strong><?php echo $this->l('I agree to the above terms and conditions.') ?></strong></label></div>
</div>

<?php $this->displayTemplate('footer') ?>
