<?php
/** @var InstallControllerHttpSystem $this */
$this->displayTemplate('header')
?>

<h2><?php echo $this->l('We are currently checking thirty bees compatibility with your system environment') ?></h2>

<p><?php echo $this->l('If you have any questions, please visit our <a href="%1$s" target="_blank">documentation</a> and <a href="%2$s" target="_blank">community forum</a>.', $this->getDocumentationLink(), $this->getForumLink()); ?></p>

<?php if ($this->tests['required']['success']): ?>
	<h3 class="okBlock"><?php echo $this->l('thirty bees compatibility with your system environment has been verified!') ?></h3>
<?php else: ?>
	<h3 class="errorBlock"><?php echo $this->l('Oops! Please correct the item(s) below, and then click "Refresh information" to test the compatibility of your new system.') ?></h3>
<?php endif; ?>
<!-- Display tests results -->
<?php foreach ($this->testsRender as $type => $categories): ?>
	<ul id="<?php echo $type ?>">
	<?php foreach ($categories as $category): ?>
        <?php if ($category['success'] == 0) { ?>
            <li class="title"><?php echo $category['title'] ?></li>
            <?php foreach ($category['checks'] as $id => $lang) { ?>
                <?php if ($this->tests[$type]['checks'][$id] != 'ok') { ?>
                    <li class="required fail"><?php echo $lang ?></li>
                <?php } ?>
            <?php } ?>
        <?php } ?>
	<?php endforeach; ?>
	</ul>
<?php endforeach; ?>

<p><input class="button" value="<?php echo $this->l('Refresh these settings')?> " type="submit" id="req_bt_refresh" /></p>

<?php $this->displayTemplate('footer') ?>
