language: php

php:
  - 5.6
  - 7.0
  - 7.3
  - 7.4

os: linux

jobs:
  fast_finish: true

services:
  - mysql

git:
  depth: 3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - COMPOSER=composer/php${TRAVIS_PHP_VERSION:0:3}/composer.json composer install --prefer-dist --no-interaction --no-progress

install:
  - php install-dev/index_cli.php --newsletter=0 --language=en --country=us --domain=thirty.bees:8888 --db_name=thirtybees --db_create=1 --name=thirtybees --email=test@thirty.bees --firstname=thirty --lastname=bees --password=thirtybees

script:
  - tests/validate.sh
  - vendor/bin/codecept run unit -c .
  - vendor/bin/codecept run integration -c .
  - phpenv config-rm xdebug.ini
  - echo "<?php if (!defined('_PS_MODE_DEV_')) define('_PS_MODE_DEV_', true);" > ./config/defines_custom.inc.php
  - php -S thirty.bees:8888 -t . >/dev/null 2>&1 &
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - sleep 10
  - vendor/bin/codecept run functional -c .
#  - vendor/bin/codecept run acceptance -c .
  - if [ -f log/2* ]; then cat log/2*; false; fi

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml

addons:
  hosts:
    - thirty.bees
