<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="This store is powered by PrestaShop" />
        <style>
            ::-moz-selection {
                background: #b3d4fc;
                text-shadow: none;
            }

            ::selection {
                background: #b3d4fc;
                text-shadow: none;
            }

            html {
                padding: 30px 10px;
                font-size: 16px;
                line-height: 1.4;
                color: #737373;
                background: #f0f0f0;
                -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
            }

            html,
            input {
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }

            body {
                max-width:600px;
                _width: 600px;
                padding: 30px 20px 50px;
                border: 1px solid #b3b3b3;
                border-radius: 4px;
                margin: 0 auto;
                box-shadow: 0 1px 10px #a7a7a7, inset 0 1px 0 #fff;
                background: #fcfcfc;
            }

            h1 {
                margin: 0 10px;
                font-size: 50px;
                text-align: center;
            }

            h1 span {
                color: #bbb;
            }
            h2 {
                color: #fad629;
                margin: 0 10px;
                font-size: 40px;
                text-align: center;
            }

            h2 span {
                color: #bbb;
                font-size: 60px;
            }

            h3 {
                margin: 1.5em 0 0.5em;
            }

            p {
                margin: 1em 0;
            }

            a {
                color: #d8b81c;
            }

            ul {
                padding: 0 0 0 40px;
                margin: 1em 0;
            }

            .container {
                max-width: 380px;
                _width: 380px;
                margin: 0 auto;
            }

            input::-moz-focus-inner {
                padding: 0;
                border: 0;
            }

            pre {
                white-space: pre-wrap;       /* Since CSS 2.1 */
                white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
                white-space: -pre-wrap;      /* Opera 4-6 */
                white-space: -o-pre-wrap;    /* Opera 7 */
                word-wrap: break-word;       /* Internet Explorer 5.5+ */
                width: 400px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2 id="errorTitle"><span>500</span> Server Error</h2>
            <p id="errorMessage">Oops, something went wrong.<br /><br />Try to refresh this page or feel free to contact us if the problem persists.</p>
            <pre><code id="encryptedError"><?php echo $markdown; ?></code></pre>
        </div>
        <script type="text/javascript">
          (function() {
            var encryptedError = document.getElementById('encryptedError');
            var previousmessage = encryptedError.innerHTML;
            var copyBtn = '<a href="javascript:copyAllText();" id="copyError" title="Copy">Copy Error</a><br/>';

            window.readAll = function() {
              encryptedError.innerHTML = copyBtn + '<span id="errorContent">' + previousmessage + '</span>';
            };

            window.copyAllText = function() {
                var errorContent = document.getElementById('errorContent');
                var range = document.createRange();
                range.selectNodeContents(errorContent);
                var sel = window.getSelection();
                sel.removeAllRanges();
                sel.addRange(range);
                try {
                    succeed = document.execCommand("copy");
                } catch(e) {
                    succeed = false;
                }
                if(succeed)
                    alert('Encrypted error copied!')
                else
                    alert('Error, try copying manually')
            }

            encryptedError.innerHTML = '<a href="javascript:readAll();">' + previousmessage.substring(0, 20) + '...</a>';

            var translations = {
              en: {
                errorTitle: '<span>500</span> Server Error',
                errorMessage: 'Oops, something went wrong.<br /><br />Try to refresh this page or feel free to contact us if the problem persists.<br/>Please make sure to expand and include the following error code in your message, so we can help you better:',
              },
              nl: {
                errorTitle: '<span>500</span> Serverfout',
                errorMessage: 'Oops, er ging iets mis.<br /><br />Probeer deze pagina te vernieuwen of neem contact op als dit het probleem niet verhelpt.<br/>Om u beter te van dienst te kunnen zijn, kunt u de onderstaande foutcode uitklappen en toevoegen aan uw bericht?',
              }
            };
            var browserLanguage = window.navigator.userLanguage || window.navigator.language;
            if (typeof translations[browserLanguage] === 'undefined') {
              if (typeof translations[browserLanguage.substring(0, 2)] !== 'undefined') {
                browserLanguage = browserLanguage.substring(0, 2);
              } else {
                browserLanguage = 'en';
              }
            }
            document.getElementById('errorTitle').innerHTML = translations[browserLanguage].errorTitle;
            document.getElementById('errorMessage').innerHTML = translations[browserLanguage].errorMessage;


          }());
        </script>
    </body>
</html>
